### ISSUE TITLE
Create mapping profiles

### ISSUE THREAD

**Issue by Hau-Hau** [leonardoporro/Detached-Mapper#54]
Hi, thanks for great library!

I wanted to ask because I don't see any example of that - is this library supports something similar to AutoMapper's CreateMap?
By that I mean any simple interface that allows to create mapping profiles.

Best regards!

**Comment by leonardoporro** [comment]
Hi @Hau-Hau, 
Sadly no, at the moment it works mostly by convention. You may post a sample of the scenario you want to support so I could work in a solution.
I started this library long ago as a patch that combined automapper and graphdiff, but then automapper became too complex and dropped the support for mapping in runtime (since version 9, createmap need to be specified for everything). I've saw automapper being removed from serveral projects because of that.
I'd like to support as much features as people ask, without doing the same.

**Comment by Hau-Hau** [comment]
It is really great that you prefer to not drop any feature. 
In terms of mapping profiles, I'm seeing a lot of potential in that feature. Mapping by convention works great for simple models and I'm amazed how it is simple with Detached mapper. However profiles makes bunch of new possibilities like support for rich domain models or aggregates etc.
Once again thanks for that project and time that you spent working on it.

**Comment by leonardoporro** [comment]
@Hau-Hau started working on profiles.
Right now it is possible to ignore or config. as association or composition on a given Type.
for example: 
`
cfg.Type<User>().Member(u => u.Name).Exclude();
`
will ignore User.Name, it doesn't matter if it comes from a DTO or anonymous or a dictionary or json.
the idea for the future is to allow doing this on a type pair basis, for example:
`
cfg.Map<User, UserDTO>().Member(u => u.Name).Exclude();
`
would exclude Name "only" if the source is a UserDTO
will work on this near the end of the year.

[tests] (https://github.com/leonardoporro/Detached-Mapper/blob/8ae250a52d8c30be1e81f9b87c69fd2b4e0f7e85/test/Detached.Mappers.EntityFramework.Tests/ProfilesTests.cs#L42)

thanks for the feedback
btw, testing and help is always welcomed!
