### ISSUE TITLE
Updating a composite collection removes one entry

### ISSUE THREAD

**Issue by Jogai** [leonardoporro/Detached-Mapper#97]
**Describe the bug**

**To Reproduce**
See https://github.com/Jogai/TellTale
Basically everything is in program.cs, but I made you collaborator so you can look at it any wich way you want.
The gist is this: I add a creator with a book. The book has a spelling error in the title so the second round I want to correct that, and add another book.

**Expected behavior**
I would expect the creator to have 2 books were the first book is updated with the correct title.

**Screenshots**
```
   ----------------------------------------------------------
   | Id | Title            | Language | CreatorId | Creator |
   ----------------------------------------------------------
   | 3  | The King's Blood | EN       | 2         | Creator |
   ----------------------------------------------------------
```
![image](https://github.com/leonardoporro/Detached-Mapper/assets/1233188/9a6b6f62-de87-4ed3-8a3c-ec07a521c0b2)

Book with Id 2 is gone..

**Desktop (please complete the following information):**
 - OS: Arch Linux & Windows 11
 - Version Detached:7.1.5 / EntityFrameworkCore:7.0.9

**Additional context**
This reproduction was actually for another issue I had, so it might very wel be a case of pebcak, but if you'd spot it I would be very happy.

**Comment by leonardoporro** [comment]
Hi @Jogai !

I've been looking at the issue and found that the library doesn't get on well with foreign keys and navigation properties (which I already knew).
So if CreatorId and CreatorId are not set at the same time, one can override the other, as the library doesn't take care or knows about the relationship of these two fields.
I have to check what to do wth that, because I would like to support this scenario, but I wouldn't like to make the mapper slower or more complex because of FKs. As FKs are intrinsic SQL concepts (see fix 6)

Meanwhile, there are some workarounds/ fixes:

fix 1: Specify both
`
new Work { Title = @"The Dragon's Path", Language = "EN", Id = 2, **CreatorId = newId, Creator = new Creator { Id = newId }** },
new Work { Title = @"The King's Blood", Language = "EN", **CreatorId = newId, Creator = new Creator { Id = newId }** },
`

fix 2: Unmap those 2, and let EF to properly set them
` 
mapperOptions.Type<Work>().Member(f => f.CreatorId).Exclude();
mapperOptions.Type<Work>().Member(f => f.Creator).Exclude();
`

fix 3: Unmap the FK, and mark Creator as [Parent]
(marking it as Parent lets the mapper know that the property should be set to the previoulsly mapped Creator instance)
`
mapperOptions.Type<Work>().Member(f => f.CreatorId).Exclude();
mapperOptions.Type<Work>().Member(f => f.Creator).Parent();
`

fix 4: Get rid of the foreign key
you can completely remove CreatorId. For mapping, just passing `new Creator { Id = x } ` would be enought and for seeding (i.e. HasData) an anonymous type can be used.
Please read "Working without explicit FKs" [here](https://github.com/leonardoporro/Detached-Mapper/wiki/Foreign-Keys)

fix 5: Use an anonymous type or a DTO that doesn't define Creator or CreatorId and let EF take care of internals, as it is what a ORM should do.
Please read [Entities as DTOs](https://github.com/leonardoporro/Detached-Mapper/wiki/Entities-as-DTOs) where I wrote about this kind of issues.

Please let me know how it goes!
Cheers

**Comment by leonardoporro** [comment]
Added this wiki entry about [Parent](https://github.com/leonardoporro/Detached-Mapper/wiki/Parents) 

@MichaelM223 pointed me that it wasn´t documented
As many other things that I need to document. Sorry, it just me, working for free in my free time :) which is very few, lastly.

**Comment by Jogai** [comment]
Hey, no problem. Since you answered I've been working on some other stuff too. I did try option 1-4 without any positive result so far, but I think you're right that option 5 is the way forward.

**Comment by leonardoporro** [comment]
[https://github.com/leonardoporro/Detached-Mapper/blob/main/contrib/Detached.Mappers.Tests.Contrib.ScottSoftware/TestUpdateScenario.cs](https://github.com/leonardoporro/Detached-Mapper/blob/main/contrib/Detached.Mappers.Tests.Contrib.ScottSoftware/TestUpdateScenario.cs)

Added and fixed your test here!
BR

**Comment by Jogai** [comment]
Awesome. Time to revive a forgotten project 😉
